# Generated by Django 5.2.3 on 2025-06-22 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Category Slug'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Product Name')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Product Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Product Image')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Product Price')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Product Discount in %')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Product Quantity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.category', verbose_name='Product Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
    ]
