# Generated by Django 5.2.3 on 2025-06-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='00000000000', max_length=25),
        ),
    ]
